**Document Based Question Answering System**

*   Base Research Paper: https://arxiv.org/pdf/1805.08092.pdf
*   Other Refereces:
      *    https://ieeexplore.ieee.org/abstract/document/9079274
      *    https://arxiv.org/pdf/1707.07328.pdf
      *    https://arxiv.org/pdf/1810.04805.pdf



*Mount Google Drive and Importing Dataset in Drive at path "gdrive/My Drive/Colab Notebook/Kaggle/"*

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')
root_path = 'gdrive/MyDrive/Colab NoteBooks/'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
pip install kaggle

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"satyamsoni","key":"d531f370613c1f272694e1852a21568e"}'}

In [ ]:
!pip install -q kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!ls ~/.kaggle
!chmod 600 /content/kaggle.json  # set permission

kaggle.json


*Adding Squad Dataset*

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#Download required dataset / competition files to a folder of your choice
!kaggle datasets download -d stanfordu/stanford-question-answering-dataset -p /content/gdrive/My\ Drive/Colab\ Notebooks/Kaggle/Squad

In [ ]:
import os
os.chdir('gdrive/My Drive/Colab Notebooks/Kaggle/Squad')  #change dir
!unzip -q stanford-question-answering-dataset.zip

*Addding glove.840B.300d Data*

In [ ]:
!kaggle datasets download -d takuok/glove840b300dtxt -p /content/gdrive/My\ Drive/Colab\ Notebooks/Kaggle/Glove

In [ ]:
import os
os.chdir('../Glove')  #change dir
!unzip -q glove840b300dtxt.zip

*Scanning Document*

In [ ]:
import os 
os.chdir('gdrive/My Drive/Colab Notebooks')

In [ ]:
pip install pdfplumber

     |████████████████████████████████| 51kB 4.2MB/s 
     |████████████████████████████████| 5.6MB 10.5MB/s 
     |████████████████████████████████| 143kB 42.8MB/s 
     |████████████████████████████████| 1.9MB 42.8MB/s 
  Created wheel for pdfplumber: filename=pdfplumber-0.5.27-cp37-none-any.whl size=32071 sha256=2c0b93f7a5416d3df9b190408934d1f7bc061d0b744828e7e0daac639ddff857
  Stored in directory: /root/.cache/pip/wheels/b4/74/fc/f7b3a1a0732209027fb48a5f4392fc40d79970b11c2ba49e71
Successfully built pdfplumber


In [ ]:
import pdfplumber
pdf = pdfplumber.open('lic_policy.pdf')
page = pdf.pages[0]
page1 = pdf.pages[1]
pdf_txt = page.extract_text() + page1.extract_text()
pdf.close()

In [ ]:
print(pdf_txt)

Life insurance is a legally enforceable contract between two parties both of whom are legally qualified to contract. It
 is therefore, necessary that the terms and conditions of the agreement must be suitably documented in a manner that
 would make it clear that both parties to the contract are Ad- idem i.e., of the same mind. Ad-Idem means that both t
he parties understand the same thing in the same sense or are of the same mind on the same subject. There must be c
onsensus or Ad-Idem between the parties to the contract.  
This is possible provided all the terms and conditions, rights and duties - privileges and obligations are properly doc
umented in terms which can be clearly interpreted in a court of law. Between two human beings sometime silence m
eans an acceptance. But as the insurer is a legal personality entitled to contract verbal discussion between parties to t
he contract is not possible and hence there is a need for documentation.  
Insurance is also a contract of utmost g

**==============================================================================================================**

**Naive Approch**

Here, we can apply naive approch i.e, converting sentences of document into vector and converting questions into vector and apply brute force method to find the cosine similarity between the sentance vector and question vector and find the min angle between them it mean find the max cosine value between *them* and sentence with max cosine value is the answer of the given question.


Steps:


*   Scan whole document and map with words as key and value as index (make dictionary).
*   Split document into sentences (dataframes) and then store each row into list.
*   Make vector of this list.

Ex: **Document** : Age(index : 1), means(2), age(3), at(4), last(5), birthday(6), Accident(7), sudden(8), unforeseen(9), and(10), involuntary(11), event(12), caused(13), by(14), external(15), visible(16), and(17), violent(18) 

Suppose sentence is "Age means ?"

**Sentence Vector** :   1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

*    Similary make User Question vector (after removing stoping words like what, how, why etc.)

*    Iterate whole sentance vector and find the cosine similarity with user question vector and find the max value (if the value is high it means angle between them is minimum and properties between both vectors matches with max probability).




In [ ]:
pdf = pdfplumber.open('lic_policy.pdf')
page = pdf.pages[0]
page1 = pdf.pages[1]
pdf_txt = page.extract_text() + page1.extract_text()
pdf.close()

In [ ]:
print(pdf_txt)

Life insurance is a legally enforceable contract between two parties both of whom are legally qualified to contract. It
 is therefore, necessary that the terms and conditions of the agreement must be suitably documented in a manner that
 would make it clear that both parties to the contract are Ad- idem i.e., of the same mind. Ad-Idem means that both t
he parties understand the same thing in the same sense or are of the same mind on the same subject. There must be c
onsensus or Ad-Idem between the parties to the contract.  
This is possible provided all the terms and conditions, rights and duties - privileges and obligations are properly doc
umented in terms which can be clearly interpreted in a court of law. Between two human beings sometime silence m
eans an acceptance. But as the insurer is a legal personality entitled to contract verbal discussion between parties to t
he contract is not possible and hence there is a need for documentation.  
Insurance is also a contract of utmost g

In [ ]:
pip install nltk

In [ ]:
pdf_txt = """Life insurance is a legally enforceable contract between two parties both of whom are legally qualified to contract. It is therefore, necessary that the terms and conditions of the agreement must be suitably documented in a manner that would make it clear that both parties to the contract are Ad- idem i.e., of the same mind. Ad-Idem means that both the parties understand the same thing in the same sense or are of the same mind on the same subject. There must be consensus or Ad-Idem between the parties to the contract.
This is possible provided all the terms and conditions, rights and duties - privileges and obligations are properly documented in terms which can be clearly interpreted in a court of law. Between two human beings sometime silence means an acceptance. But as the insurer is a legal personality entitled to contract verbal discussion between parties to the contract is not possible and hence there is a need for documentation.
Insurance is also a contract of utmost good faith and enforced only in the distant future. It is therefore necessary that the declarations made by both the parties should be put in black and white for future reference. Any suppression, willful and material shall make the contract void. The insured, therefore, has a duty to declare all that he knows about himself, his health, his financial status in answering questions contained in the proposal form and other ancillary documents which may be required by the insurer.
Age is an important factor in deciding the quantum of premium against a policy. The document proving the age, i.e. age proof must be reliable and the insured has to undertake as to its truthfulness.
Non-standard age proofs are those which are comparatively less reliable and therefore the insurer accepts them with a pinch of salt. In other words the insurer takes certain precautions before accepting such age proofs as final.
Proof of income is the document may become necessary whenever the sum proposed is very high. Normally a sum proposed which is seven to eight times of the declared income is acceptable for insurance. But proposals do come to the insurer when the known source of income of the proposer is much less compared to the amount of insurance desired. A service holder normally does not face this problem as his sources of income are verifiable.
In case of business people, the assessed income is at times much less compared to what is a desirable income for the amount of insurance desired. In such cases the insurer at times calls for assessed income tax returns, or Chartered Accountant’s certificate etc. Such precautions are necessary to eliminate the possibility of moral hazard.
Policy Contract is the policy document is a detailed document and it is the Evidence of the insurance contract which mentions all the terms and conditions of the insurance. The insured buys not the policy contract, but the right to the sum of money and its future delivery. The insurer on its part promises to pay a sum of money, provided of course the insured keeps its part of promise of paying the installments of premium as scheduled.
The pre-amble to the insurance contract makes the above statement clear and states that this policy is issued subject to the conditions and privileges printed on the back of the policy. The endorsements placed on the policy shall also be part of the policy and it also makes a reference to the proposal form saying that that the statements given in the proposal form are the basis of the contract.
The schedule which is printed on the policy document identifies the office which has issued the policy. It states the name of the policyholder, the date of commencement of the policy, an identification number of the policy called policy number. This number is extremely useful for making any reference to the insurer relating to this policy. This shall avoid needless delay.
Beneficiary’s name is also mentioned along with address.
It is necessary to check that it is correct and any mistake should be immediately pointed out for correction. A mistake in the address may misdirect the premium notices and any other future correspondence. It also states the name of the nominee and the date upto which premium has to be paid. The schedule goes on to mention, the type of policy, on the happening of which, the sum assured is payable and to whom it is payable. It of course also mentions when and how long the premium is to be paid.
The policy document is signed by an official of the insurer and dated and stamped as per the provision of the Stamp Act to make it a completely legally enforceable document.
An assignment of a policy in favour of another person or institution can be effected by an endorsement on the policy. Re-assignment can also be done by a subsequent endorsement on the same policy.As a nomination is automatically cancelled due to an assignment, after re-assignment, it is necessary to make a fresh nomination.
In Duplicate policy a policy document is a valuable document and can be used for mortgage etc. Loss of policy document does not absolve the insurer from the liability of payment of policy proceeds when the claim arises. The claim can be settled on the claimants, furnishing an indemnity bond jointly with one surety.
If a policy is irrevocably lost, a duplicate policy can be issued, after following a certain procedure like the insurer satisfies itself of the circumstances leading to loss and being so satisfied the insurer insists upon an advertisement in a news paper, production of an indemnity bond and payment of policy preparation charges and there after a duplicate policy is issued.
Generally nomination is made at the time of taking a policy. In case it is not done, it is possible to make nomination subsequently by an endorsement on the policy. It is also possible to change a nomination subsequently by an endorsement. After marriage, such change in nomination is normally required.
Life insurance being a legally enforceable contract, needs to be documented with details of the rights and obligations of the parties to the contract. Proposal form duly filled in and signed by the proposer is the first document which forms the basis of the contract.
Every time, the insured pays the premium, he receives a premium receipt. The premium needs to be paid in time, non- payment of premium leads to policy-lapses. Re-instatement of the cover is called revival of the policy.
If the policy is not revived, the policy can become a paid up policy for a reduced sum assured under certain conditions.
The policy document mentions in detail all the rights and obligations of the policyholder. The agent is advised to explain the various provisions of the policy to the policyholder.
The wordings in the policy document are of technical nature and hence the need for explaining. If there are certain endorsements on the policy, that need to be explained too.
It needs to be explained that the policy is a valuable document and needs to be kept in safe custody and in the knowledge of the close relatives.
"""

import nltk
nltk.download('punkt')
tokens = nltk.sent_tokenize(pdf_txt)
for t in tokens:
    print(t, "\n")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
Life insurance is a legally enforceable contract between two parties both of whom are legally qualified to contract. 

It is therefore, necessary that the terms and conditions of the agreement must be suitably documented in a manner that would make it clear that both parties to the contract are Ad- idem i.e., of the same mind. 

Ad-Idem means that both the parties understand the same thing in the same sense or are of the same mind on the same subject. 

There must be consensus or Ad-Idem between the parties to the contract. 

This is possible provided all the terms and conditions, rights and duties - privileges and obligations are properly documented in terms which can be clearly interpreted in a court of law. 

Between two human beings sometime silence means an acceptance. 

But as the insurer is a legal personality entitled to contract verbal discussion between parties to the con

In [ ]:
pip install -U gensim

     |████████████████████████████████| 23.9MB 1.5MB/s 
  Found existing installation: gensim 3.6.0
    Uninstalling gensim-3.6.0:
      Successfully uninstalled gensim-3.6.0


In [ ]:
import re
import gensim
from gensim.parsing.preprocessing import remove_stopwords

def clean_sentence(sentence, stopwords=False):
  sentence = sentence.lower().strip()
  sentence = re.sub(r'[^a-z0-9\s]', '', sentence)
  if stopwords:
    sentence = remove_stopwords(sentence)
  return sentence

def get_cleaned_sentences(tokens, stopwords=False):
  cleaned_sentences = []
  for row in tokens:
    cleaned = clean_sentence(row, stopwords)
    cleaned_sentences.append(cleaned)
  return cleaned_sentences



/usr/local/lib/python3.7/dist-packages/gensim/similarities/__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)


In [ ]:
cleaned_sentences = get_cleaned_sentences(tokens, stopwords=True)
cleaned_sentences_with_stopwords = get_cleaned_sentences(tokens, stopwords=False)
print(cleaned_sentences)
print(cleaned_sentences_with_stopwords)

['life insurance legally enforceable contract parties legally qualified contract', 'necessary terms conditions agreement suitably documented manner clear parties contract ad idem mind', 'adidem means parties understand thing sense mind subject', 'consensus adidem parties contract', 'possible provided terms conditions rights duties privileges obligations properly documented terms clearly interpreted court law', 'human beings silence means acceptance', 'insurer legal personality entitled contract verbal discussion parties contract possible need documentation', 'insurance contract utmost good faith enforced distant future', 'necessary declarations parties black white future reference', 'suppression willful material shall contract void', 'insured duty declare knows health financial status answering questions contained proposal form ancillary documents required insurer', 'age important factor deciding quantum premium policy', 'document proving age', 'age proof reliable insured undertake tru

In [ ]:
import numpy
sentences = cleaned_sentences_with_stopwords
sentence_words = [[word for word in document.split()]
                  for document in sentences]

from gensim import corpora
dictionary = corpora.Dictionary(sentence_words)
for key, value in dictionary.items():
  print(key, ' : ', value)

0  :  a
1  :  are
2  :  between
3  :  both
4  :  contract
5  :  enforceable
6  :  insurance
7  :  is
8  :  legally
9  :  life
10  :  of
11  :  parties
12  :  qualified
13  :  to
14  :  two
15  :  whom
16  :  ad
17  :  agreement
18  :  and
19  :  be
20  :  clear
21  :  conditions
22  :  documented
23  :  idem
24  :  ie
25  :  in
26  :  it
27  :  make
28  :  manner
29  :  mind
30  :  must
31  :  necessary
32  :  same
33  :  suitably
34  :  terms
35  :  that
36  :  the
37  :  therefore
38  :  would
39  :  adidem
40  :  means
41  :  on
42  :  or
43  :  sense
44  :  subject
45  :  thing
46  :  understand
47  :  consensus
48  :  there
49  :  all
50  :  can
51  :  clearly
52  :  court
53  :  duties
54  :  interpreted
55  :  law
56  :  obligations
57  :  possible
58  :  privileges
59  :  properly
60  :  provided
61  :  rights
62  :  this
63  :  which
64  :  acceptance
65  :  an
66  :  beings
67  :  human
68  :  silence
69  :  sometime
70  :  as
71  :  but
72  :  discussion
73  :  documentation

In [ ]:
import pprint
bow_corpus = [dictionary.doc2bow(text) for text in sentence_words]
for sent, embedding in zip(sentences, bow_corpus):
  print(sent)
  print(embedding)

life insurance is a legally enforceable contract between two parties both of whom are legally qualified to contract
[(0, 1), (1, 1), (2, 1), (3, 1), (4, 2), (5, 1), (6, 1), (7, 1), (8, 2), (9, 1), (10, 1), (11, 1), (12, 1), (13, 1), (14, 1), (15, 1)]
it is therefore necessary that the terms and conditions of the agreement must be suitably documented in a manner that would make it clear that both parties to the contract are ad idem ie of the same mind
[(0, 1), (1, 1), (3, 1), (4, 1), (7, 1), (10, 2), (11, 1), (13, 1), (16, 1), (17, 1), (18, 1), (19, 1), (20, 1), (21, 1), (22, 1), (23, 1), (24, 1), (25, 1), (26, 2), (27, 1), (28, 1), (29, 1), (30, 1), (31, 1), (32, 1), (33, 1), (34, 1), (35, 3), (36, 4), (37, 1), (38, 1)]
adidem means that both the parties understand the same thing in the same sense or are of the same mind on the same subject
[(1, 1), (3, 1), (10, 1), (11, 1), (25, 1), (29, 1), (32, 4), (35, 1), (36, 5), (39, 1), (40, 1), (41, 1), (42, 1), (43, 1), (44, 1), (45, 1), (46,

In [ ]:
user_question = "When can a duplicate policy be issued?"

In [ ]:
question = clean_sentence(user_question, stopwords=False)
question_embedding = dictionary.doc2bow(question.split())
print(user_question, "\n", question_embedding)

When can a duplicate policy be issued? 
 [(0, 1), (19, 1), (50, 1), (132, 1), (183, 1), (228, 1), (308, 1)]


In [ ]:
import sklearn
from sklearn.metrics.pairwise import cosine_similarity

def retrieveAndPrintFAQAnswer(question_embedding, sentence_embeddings, sentences):
  max_sim = -1
  index_sim = -1
  for index, embedding in enumerate(sentence_embeddings):
    sim = cosine_similarity(embedding, question_embedding)[0][0]
    print(index, sim, sentences[index])
    if sim > max_sim:
      max_sim = sim
      index_sim = index
  
  return index_sim
index = retrieveAndPrintFAQAnswer(question_embedding, bow_corpus, sentences)  

0 1.0 life insurance is a legally enforceable contract between two parties both of whom are legally qualified to contract
1 1.0 it is therefore necessary that the terms and conditions of the agreement must be suitably documented in a manner that would make it clear that both parties to the contract are ad idem ie of the same mind
2 0.7071067811865475 adidem means that both the parties understand the same thing in the same sense or are of the same mind on the same subject
3 0.4472135954999579 there must be consensus or adidem between the parties to the contract
4 1.0 this is possible provided all the terms and conditions rights and duties  privileges and obligations are properly documented in terms which can be clearly interpreted in a court of law
5 0.4472135954999579 between two human beings sometime silence means an acceptance
6 1.0 but as the insurer is a legal personality entitled to contract verbal discussion between parties to the contract is not possible and hence there is a nee

In [ ]:
print("Question: ", question)
print("Answer: ", sentences[index])

Question:  when can a duplicate policy be issued
Answer:  life insurance is a legally enforceable contract between two parties both of whom are legally qualified to contract


**==============================================================================================================**

***Word Embedding Technique***



1.   Word2Vec Embedding Technique
2.   Glove Embedding Technique



***Using Word2Vec Model Approch***

In these appproch we takes input of large corpus words and produces a vector space, typically of several hundreds dimensions, with each unique word in the corpus being assigned a corresponding vector in the space.

Word vectors are positioned in the vector space such that words that share common contexts in the corpus are located in close proximity to one another in the space. Word2Vec is a particularly computationally-efficient predictive model for learning word embeddings from raw text.

**Working**

Word2Vec is a simple neural network with a single hidden layer, and like all neural networks, it has weights, and during training, its goal is to adjust those weights to reduce a loss function. However, Word2Vec is not going to be used for the task it was trained on, instead, we will just take its hidden weights, use them as our word embeddings, and toss the rest of the model (this came out a little bit evil).


In [ ]:
from gensim.models import Word2Vec
import gensim.downloader as api

v2w_model = None
try:
  v2w_model = gensim.models.Keyedvectors.load('./w2vecmodel.mod')
  print("w2v Model Successfully loaded")
except:
  v2w_model = api.load('word2vec-google-news-300')
  v2w_model.save("./w2vecmodel.mod")
  print("w2v Model Saved")

w2vec_embedding_size = len(v2w_model['pc'])  

[==================================================] 100.0% 1662.8/1662.8MB downloaded
w2v Model Saved


In [ ]:
def getWordVec(word, model):
  samp = model['pc']
  vec = [0]*len(samp)
  try:
    vec = model[word]
  except:
    vec = [0]*len(samp)
  return (vec)


def getPhraseEmbedding(phrase, embeddingmodel):
  samp = getWordVec('computer', embeddingmodel)
  vec = numpy.array([0]*len(samp))
  den = 0;
  for word in phrase.split():
    den = den+1
    vec = vec+numpy.array(getWordVec(word, embeddingmodel))
  return vec.reshape(1, -1)

In [ ]:
sent_embeddings = []
for sent in sentences:
  sent_embeddings.append(getPhraseEmbedding(sent, v2w_model))

question_embedding = getPhraseEmbedding(question, v2w_model)
index = retrieveAndPrintFAQAnswer(question_embedding, sent_embeddings, cleaned_sentences_with_stopwords)

0 0.5513437234038394 life insurance is a legally enforceable contract between two parties both of whom are legally qualified to contract
1 0.7025787291556694 it is therefore necessary that the terms and conditions of the agreement must be suitably documented in a manner that would make it clear that both parties to the contract are ad idem ie of the same mind
2 0.6070676295451412 adidem means that both the parties understand the same thing in the same sense or are of the same mind on the same subject
3 0.6058007155185451 there must be consensus or adidem between the parties to the contract
4 0.6729521680764039 this is possible provided all the terms and conditions rights and duties  privileges and obligations are properly documented in terms which can be clearly interpreted in a court of law
5 0.430919800661395 between two human beings sometime silence means an acceptance
6 0.6073519392489676 but as the insurer is a legal personality entitled to contract verbal discussion between parti

In [ ]:
print("Question: ", question)
print("Answer: ", cleaned_sentences_with_stopwords[index])

Question:  when can a duplicate policy be issued
Answer:  if a policy is irrevocably lost a duplicate policy can be issued after following a certain procedure like the insurer satisfies itself of the circumstances leading to loss and being so satisfied the insurer insists upon an advertisement in a news paper production of an indemnity bond and payment of policy preparation charges and there after a duplicate policy is issued


**==============================================================================================================**

***Using Glove Embedding Approch***

Glove is an alternate approch to build word embeddings using matrix factorization techniques on the word-word co-occurance matrix.

A large matrix of co-occurrence information is constructed and you count each “word” (the rows), and how frequently we see this word in some “context” (the columns) in a large corpus. Usually, we scan our corpus in the following manner: for each term, we look for context terms within some area defined by a window-size before the term and a window-size after the term. Also, we give less weight for more distant words.

The number of “contexts” is, of course, large, since it is essentially combinatorial in size. So then we factorize this matrix to yield a lower-dimensional matrix, where each row now yields a vector representation for each word. In general, this is done by minimizing a “reconstruction loss”. This loss tries to find the lower-dimensional representations which can explain most of the variance in the high-dimensional data.

In [ ]:
glove_model = None
try:
  glove_model = gensim.models.Keyedvectors.load('./glovemodel.mod')
  print("Glove Model Successfully loaded")
except:
  glove_model = api.load('glove-twitter-25')
  glove_model.save("./glovemodel.mod")
  print("Glove Model Saved")

glove_embedding_size = len(glove_model['pc'])

[==================================================] 100.0% 104.8/104.8MB downloaded
Glove Model Saved


In [ ]:
sent_embeddings = []
for sent in cleaned_sentences:
  sent_embeddings.append(getPhraseEmbedding(sent, glove_model))

question_embedding = getPhraseEmbedding(question, glove_model)
retrieveAndPrintFAQAnswer(question_embedding, sent_embeddings, cleaned_sentences_with_stopwords)

0 0.9022455392443606 life insurance is a legally enforceable contract between two parties both of whom are legally qualified to contract
1 0.9084665468647729 it is therefore necessary that the terms and conditions of the agreement must be suitably documented in a manner that would make it clear that both parties to the contract are ad idem ie of the same mind
2 0.9324847200286663 adidem means that both the parties understand the same thing in the same sense or are of the same mind on the same subject
3 0.8267337040436452 there must be consensus or adidem between the parties to the contract
4 0.8828094588463636 this is possible provided all the terms and conditions rights and duties  privileges and obligations are properly documented in terms which can be clearly interpreted in a court of law
5 0.849249967948168 between two human beings sometime silence means an acceptance
6 0.9104672345379424 but as the insurer is a legal personality entitled to contract verbal discussion between parti

59

In [ ]:
print("Question: ", question)
print("Answer: ", cleaned_sentences_with_stopwords[index])

Question:  when can a duplicate policy be issued
Answer:  if a policy is irrevocably lost a duplicate policy can be issued after following a certain procedure like the insurer satisfies itself of the circumstances leading to loss and being so satisfied the insurer insists upon an advertisement in a news paper production of an indemnity bond and payment of policy preparation charges and there after a duplicate policy is issued


**==============================================================================================================**

**Question Answering with a Fine-Tuned BERT**

Bidirectional Encoder Representations from Transformers

Instead of looking at words in isolation, BERT, a transformer based model attempts to use the context of words to get embeddings. BERT uses several concepts of deep learning come up with a model that looks at context in a bidirectional fashion, leveraging information from the entire sentences as a whole through self-attention. 

Example: Suppose Question is "How I can cross a road when their is no zebra crossing." and this question very similar to query "How I can cross road on zebra crossing." and thier is a chance that above two method give wrong answers but could handle that question. And we don't remove stoping words in the document because if it remove word like in above example "no" meaning of whole sentance become change. Bert uses stoping words to make relations between words.

*What is Model Fine-Tuning?*

BERT (Bidirectional Encoder Representations from Transformers) is a big neural network architecture, with a huge number of parameters, that can range from 100 million to over 300 million. So, training a BERT model from scratch on a small dataset would result in overfitting.

So, it is better to use a pre-trained BERT model that was trained on a huge dataset, as a starting point. We can then further train the model on our relatively smaller dataset and this process is known as model fine-tuning.

*   Installing the Hugging Face library



In [ ]:
!pip install transformers==3.1.0

     |████████████████████████████████| 890kB 9.0MB/s 
     |████████████████████████████████| 3.0MB 16.3MB/s 
     |████████████████████████████████| 1.2MB 51.0MB/s 
     |████████████████████████████████| 901kB 17.5MB/s 




*   Load Fine-Tuned BERT-large




In [ ]:
import torch
from transformers import BertForQuestionAnswering
model = BertForQuestionAnswering.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')



*   Load the tokenizer



In [ ]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')

answer text contains the pdf content

In [ ]:
answer_text = """The ability of the machine to infer knowledge from
the user documents can be tested based on its ability to answer
the question asked. Conventional Artificial Neural Network
(ANN) models for knowledge extraction only answer to the
questions which are simple and objective as they don't analyze
the questions and don't try to understand what really the content
of document mean. The proposed question answering system
(QAS) uses deep cases along with ANN to understand the
contents of the documents. We divide the sentences of natural
language into knowledge units and assign deep case to each word
to improve the quality of knowledge extraction."""

question = "How to improve the quality of knowledge extraction?"

Apply the tokenizer to the input text, treating them as a text-pair.

In [ ]:
input_ids = tokenizer.encode(question, answer_text, max_length=512, truncation=True)
print('The input has a total of {:} tokens.'.format(len(input_ids)))


The input has a total of 130 tokens.


Just to see exactly what the tokenizer is doing, let's print out the tokens with their IDs.

In [ ]:
tokens = tokenizer.convert_ids_to_tokens(input_ids)
for token, id in zip(tokens, input_ids):
    if id == tokenizer.sep_token_id:
        print('')
    print('{:<12} {:>6,}'.format(token, id))

    if id == tokenizer.sep_token_id:
        print('')

[CLS]           101
how           2,129
to            2,000
improve       5,335
the           1,996
quality       3,737
of            1,997
knowledge     3,716
extraction   14,676
?             1,029

[SEP]           102

the           1,996
ability       3,754
of            1,997
the           1,996
machine       3,698
to            2,000
in            1,999
##fer         7,512
knowledge     3,716
from          2,013
the           1,996
user          5,310
documents     5,491
can           2,064
be            2,022
tested        7,718
based         2,241
on            2,006
its           2,049
ability       3,754
to            2,000
answer        3,437
the           1,996
question      3,160
asked         2,356
.             1,012
conventional  7,511
artificial    7,976
neural       15,756
network       2,897
(             1,006
ann           5,754
)             1,007
models        4,275
for           2,005
knowledge     3,716
extraction   14,676
only          2,069
answer        3,43

We can concatenated the question and answer_text together, but BERT still needs a a way to distinguish them. BERT has two special "Segment" embeddings, one for segment "A" and one for segment "B". Before the word embeddings go into the BERT layers, the segment A embedding needs to be added to the question tokens, and the segment B embedding needs to be added to each of the answer_text tokens.
These handled by the transformer library and all we need to do is specify '0' and '1' for the token.

In [ ]:
sep_index = input_ids.index(tokenizer.sep_token_id)
num_seg_a = sep_index + 1
num_seg_b = len(input_ids) - num_seg_a
#Here We Construct the list of 0s and 1s.
segment_ids = [0]*num_seg_a + [1]*num_seg_b
# There should be a segment_id for every input token.
assert len(segment_ids) == len(input_ids)

Here we feed answer_text and question into model

In [ ]:
start_scores, end_scores = model(torch.tensor([input_ids]), token_type_ids=torch.tensor([segment_ids]))

Here we find the highest 'start' and 'end' scores and the combine the tokens in the answer and print the answer

In [ ]:
answer_start = torch.argmax(start_scores)
answer_end = torch.argmax(end_scores)

answer = ' '.join(tokens[answer_start:answer_end+1])

print('Answer: "' + answer + '"')

Answer: "divide the sentences of natural language into knowledge units and assign deep case to each word"


We can reconstruct any words that got broken down into subwords.

In [ ]:
answer = tokens[answer_start]
answer = tokens[answer_start]

# Select the remaining answer tokens and join them with whitespace.
for i in range(answer_start + 1, answer_end + 1):
  # If it's a subword token, then recombine it with the previous token.
    if tokens[i][0:2] == '##':
        answer += tokens[i][2:]
        # Otherwise, add a space then the token.
    else:
        answer += ' ' + tokens[i]
print('Answer: "' + answer + '"')

Answer: "divide the sentences of natural language into knowledge units and assign deep case to each word"


Here we make a function of overall code

In [ ]:
def answer_question(question, answer_text):

    input_ids = tokenizer.encode(question, answer_text, max_length=512, truncation=True)

    print('Query has {:,} tokens.\n'.format(len(input_ids)))

    sep_index = input_ids.index(tokenizer.sep_token_id)

    num_seg_a = sep_index + 1

    num_seg_b = len(input_ids) - num_seg_a

    segment_ids = [0]*num_seg_a + [1]*num_seg_b

    assert len(segment_ids) == len(input_ids)

    start_scores, end_scores = model(torch.tensor([input_ids]), token_type_ids=torch.tensor([segment_ids]))

    all_tokens = tokenizer.convert_ids_to_tokens(input_ids)

    #print(' '.join(all_tokens[torch.argmax(start_scores) : torch.argmax(end_scores)+1]))
    #print(f'score: {torch.max(start_scores)}')
    score = float(torch.max(start_scores))
    answer_start = torch.argmax(start_scores)
    answer_end = torch.argmax(end_scores)
    tokens = tokenizer.convert_ids_to_tokens(input_ids)
    answer = tokens[answer_start]

    for i in range(answer_start + 1, answer_end + 1):

        if tokens[i][0:2] == ' ':
            answer += tokens[i][2:]

        else:
            answer += ' ' + tokens[i]
    return answer, score
    #print('Answer: "' + answer + '"')

Here lets call the function and pass question as 1st parameter and content as 2nd parameter and we get the final answer

In [ ]:
answer_question(question, answer_text)

Query has 130 tokens.



('divide the sentences of natural language into knowledge units and assign deep case to each word',
 6.490677356719971)

Limitation of Bert that it process only upto 512 tokens So we can implement new method to make it for whole document.


In [ ]:
pdf_txt

'Life insurance is a legally enforceable contract between two parties both of whom are legally qualified to contract. It is therefore, necessary that the terms and conditions of the agreement must be suitably documented in a manner that would make it clear that both parties to the contract are Ad- idem i.e., of the same mind. Ad-Idem means that both the parties understand the same thing in the same sense or are of the same mind on the same subject. There must be consensus or Ad-Idem between the parties to the contract.\nThis is possible provided all the terms and conditions, rights and duties - privileges and obligations are properly documented in terms which can be clearly interpreted in a court of law. Between two human beings sometime silence means an acceptance. But as the insurer is a legal personality entitled to contract verbal discussion between parties to the contract is not possible and hence there is a need for documentation.\nInsurance is also a contract of utmost good fait

In [ ]:
user_question

'When can a duplicate policy be issued?'


We need to split the sentences according to tokens i.e, we can split upto 512 tokens after that we need to add some special token like [SEP], [CLS].

Tokenization: Tokenization is the process of converting a string of text into a list of tokens (individual words/punctuation) and/or token IDs (integers that map a word to a vector representation of that word in an embedding array).



*   Here we are using the tokenizers encode_plus method to create our tokens from the text string
*   add_special_tokens=True adds special BERT tokens like [CLS], [SEP], and [PAD] to our new ‘tokenized’ encodings
*   max_length=512 tells the encoder the target length of our encodings
*   truncation=True ensures we cut any sequences that are longer than the
specified max_length .
*   padding="max_length" tells the encoder to pad any sequences that are shorter
than the max_length with padding tokens.



In [ ]:
tokens = tokenizer.encode_plus(user_question, pdf_txt, add_special_tokens=True, max_length=512, truncation=True, padding="max_length")
tokens

{'input_ids': [101, 2043, 2064, 1037, 24473, 3343, 2022, 3843, 1029, 102, 2166, 5427, 2003, 1037, 10142, 16306, 3085, 3206, 2090, 2048, 4243, 2119, 1997, 3183, 2024, 10142, 4591, 2000, 3206, 1012, 2009, 2003, 3568, 1010, 4072, 2008, 1996, 3408, 1998, 3785, 1997, 1996, 3820, 2442, 2022, 4848, 8231, 8832, 1999, 1037, 5450, 2008, 2052, 2191, 2009, 3154, 2008, 2119, 4243, 2000, 1996, 3206, 2024, 4748, 1011, 8909, 6633, 1045, 1012, 1041, 1012, 1010, 1997, 1996, 2168, 2568, 1012, 4748, 1011, 8909, 6633, 2965, 2008, 2119, 1996, 4243, 3305, 1996, 2168, 2518, 1999, 1996, 2168, 3168, 2030, 2024, 1997, 1996, 2168, 2568, 2006, 1996, 2168, 3395, 1012, 2045, 2442, 2022, 10465, 2030, 4748, 1011, 8909, 6633, 2090, 1996, 4243, 2000, 1996, 3206, 1012, 2023, 2003, 2825, 3024, 2035, 1996, 3408, 1998, 3785, 1010, 2916, 1998, 5704, 1011, 14310, 1998, 14422, 2024, 7919, 8832, 1999, 3408, 2029, 2064, 2022, 4415, 10009, 1999, 1037, 2457, 1997, 2375, 1012, 2090, 2048, 2529, 9552, 8811, 4223, 2965, 2019, 9920, 1

It return a dictionary containing three key-value pairs, input_ids ,
token_type_ids , and attention_mask .
We have also added return_tensors='pt' to return PyTorch tensors from the
tokenizer (rather than Python lists).

In [ ]:
tokens = tokenizer.encode_plus(pdf_txt, add_special_tokens=False, return_tensors='pt')
tokens

Token indices sequence length is longer than the specified maximum sequence length for this model (1395 > 512). Running this sequence through the model will result in indexing errors


{'input_ids': tensor([[2166, 5427, 2003,  ..., 2485, 9064, 1012]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1]])}

In [ ]:
input_id_chunks = tokens['input_ids'][0].split(510)
mask_chunks = tokens['attention_mask'][0].split(510)

for tensor in input_id_chunks:
  print(len(tensor))

510
510
375


In [ ]:
a = torch.arange(10)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.cat(
    [torch.Tensor([101]), a, torch.Tensor([102])]
)

tensor([101.,   0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9., 102.])

***Preparing The Chunks***

Now we have our tokenized tensor; we need to break it into chunks of no more than 510 tokens. We choose 510 rather than 512 to leave two places spare to add our [CLS] and [SEP] tokens.

***Split***


We apply the split method to both our input IDs and attention mask tensors (we
don’t need the token type IDs and can discard them). Now we have three chunks for each tensor set. Note that we will need to add padding to the final chunk as it will not satisfy the tensor size of 512 required by BERT.


***CLS and SEP***


Next, we add the start of sequence [CLS] and separator [SEP] tokens. For this, we can use the torch.cat function, which concatenates a list of tensors.
Our tokens are already in token ID format, so we can refer to the special tokens
table above to create the token ID versions of our [CLS] and [SEP] tokens.
Because we are doing this for multiple tensors, we place the torch.cat function into
a for-loop and perform the concatenation for each of our chunks individually.
Additionally, our attention mask chunks are concatenated with 1s rather than 101
and 102. We do this because the attention mask does not contain token IDs but
instead a set of 1s and 0s.
Zeros in the attention mask represent the location of padding tokens (which we will
add next), and as [CLS] and [SEP] are not padding tokens, they are represented
with 1s.

***Padding***


We need to add padding to our tensor chunks to ensure they satisfy the 512 tensorlength required by BERT. Our first two chunks don’t require any padding as they already satisfy this length requirement, but the final chunks do.
To check if a chunk requires padding, we add an if-statement that checks the tensor length. If the tensor is shorter than 512 tokens, we add padding using the torch.cat function. We should add this statement to the same for-loop where we add our [CLS] and [SEP] tokens — if you need help with this, I’ve included the full scripts at the end of the article.


In [ ]:
chunksize = 512

input_id_chunks = list(tokens['input_ids'][0].split(chunksize - 2))
mask_chunks = list(tokens['attention_mask'][0].split(chunksize - 2))

for i in range(len(input_id_chunks)):
    input_id_chunks[i] = torch.cat([
        torch.tensor([101]), input_id_chunks[i], torch.tensor([102])
    ])
    mask_chunks[i] = torch.cat([
        torch.tensor([1]), mask_chunks[i], torch.tensor([1])
    ])

    pad_len = chunksize - input_id_chunks[i].shape[0]
    if pad_len > 0:
        input_id_chunks[i] = torch.cat([
            input_id_chunks[i], torch.Tensor([0] * pad_len)
        ])
        mask_chunks[i] = torch.cat([
            mask_chunks[i], torch.Tensor([0] * pad_len)
        ])

for chunk in input_id_chunks:
    print(chunk)

tensor([  101,  2166,  5427,  2003,  1037, 10142, 16306,  3085,  3206,  2090,
         2048,  4243,  2119,  1997,  3183,  2024, 10142,  4591,  2000,  3206,
         1012,  2009,  2003,  3568,  1010,  4072,  2008,  1996,  3408,  1998,
         3785,  1997,  1996,  3820,  2442,  2022,  4848,  8231,  8832,  1999,
         1037,  5450,  2008,  2052,  2191,  2009,  3154,  2008,  2119,  4243,
         2000,  1996,  3206,  2024,  4748,  1011,  8909,  6633,  1045,  1012,
         1041,  1012,  1010,  1997,  1996,  2168,  2568,  1012,  4748,  1011,
         8909,  6633,  2965,  2008,  2119,  1996,  4243,  3305,  1996,  2168,
         2518,  1999,  1996,  2168,  3168,  2030,  2024,  1997,  1996,  2168,
         2568,  2006,  1996,  2168,  3395,  1012,  2045,  2442,  2022, 10465,
         2030,  4748,  1011,  8909,  6633,  2090,  1996,  4243,  2000,  1996,
         3206,  1012,  2023,  2003,  2825,  3024,  2035,  1996,  3408,  1998,
         3785,  1010,  2916,  1998,  5704,  1011, 14310,  1998, 

Here we can rejoining the splited tokens

In [ ]:
for tensor in range(len(input_id_chunks)):
  ans = answer_question(user_question, ' '.join(tokenizer.convert_ids_to_tokens(input_id_chunks[tensor])))
  print(ans)

Query has 512 tokens.

('[SEP]', 1.9390361309051514)
Query has 512 tokens.

('[CLS] when can a duplicate policy be issued ? [SEP] [CLS] precautions are necessary to eliminate the possibility of moral hazard . policy contract is the policy document is a detailed document and it is the evidence of the insurance contract which mentions all the terms and conditions of the insurance . the ins # # ur ##ed buys not the policy contract , but the right to the sum of money and its future delivery . the ins # # ur ##er on its part promises to pay a sum of money , provided of course the ins # # ur ##ed keeps its part of promise of paying the installment # # s of premium as scheduled . the pre - am # # b ##le to the insurance contract makes the above statement clear and states that this policy is issued subject to the conditions and privileges printed on the back of the policy . the endorsement # # s placed on the policy shall also be part of the policy and it also makes a reference to the proposal

In [ ]:
def expand_split_sentences(pdf_txt):
  import nltk
  nltk.download('punkt')
  new_chunks = nltk.sent_tokenize(pdf_txt)
  length = len(new_chunks)
  #for i in range(length):
    #tmp_token = tokenizer.encode(new_chunks[i])
    #print('The input has a total of {:} tokens.'.format(len(tmp_token)))

  new_df = [];
  for i in range(length):
    paragraph = ""
    for j in range(i, length):
      #tmp_str = paragraph + new_chunks[j]
      tmp_token = tokenizer.encode(paragraph + new_chunks[j])
      length_token = len(tmp_token)
      if length_token < 510:
        #print(length_token)
        paragraph = paragraph + new_chunks[j]
      else:
        #print(length_token)
        break;
    #print(len(tokenizer.encode(paragraph)))
    new_df.append(paragraph)
  return new_df
  #for i in new_df:
    #print(i)

In [ ]:
fdi = """Make in India is an initiative which was launched on September 25, 2014, to facilitate investment, foster innovation, building best in class infrastructure, and making India a hub for manufacturing, design, and innovation. The development of a robust manufacturing sector continues to be a key priority of the Indian Government. It was one of the first 'Vocal for Local' initiatives that exposed India's manufacturing domain to the world. The sector has the potential to not only take economic growth to a higher trajectory but also to provide employment to a large pool of our young labour force.
Make in India initiative has made significant achievements and presently focuses on 27 sectors under Make in India 2.0. Department for Promotion of Industry and Internal Trade is coordinating action plans for manufacturing sectors, while Department of Commerce is coordinating service sectors.
The Government of India is making continuous efforts under Investment Facilitation for implementation of Make in India action plans to identify potential investors. Support is being provided to Indian Missions abroad and State Governments for organising events, summits, road-shows and other promotional activities to attract investment in the country under the Make in India banner. Investment Outreach activities are being carried out for enhancing International co-operation for promoting FDI and improve Ease of Doing Business in the country.
India has registered its highest ever annual FDI Inflow of US $74.39 billion (provisional figure) during the last financial year 2019-20 as compared to US $ 45.15 billion in 2014-2015. In the last six financial years (2014-20), India has received FDI inflow worth US$ 358.30 billion which is 53 percent of the FDI reported in the last 20 years (US$ 681.87 billion).
Steps taken to improve Ease of Doing Business include simplification and rationalization of existing processes. As a result of the measures taken to improve the country’s investment climate, India jumped to 63rd place in World Bank’s Ease of Doing Business ranking as per World Bank’s Doing Business Report (DBR) 2020. This is driven by reforms in the areas of Starting a Business, Paying Taxes, Trading Across Borders, and Resolving Insolvency.
Recently, Government has taken various steps in addition to ongoing schemes to boost domestic and foreign investments in India. These include the National Infrastructure Pipeline, Reduction in Corporate Tax, easing liquidity problems of NBFCs and Banks, policy measures to boost domestic manufacturing. Government of India has also promoted domestic manufacturing of goods through public procurement orders, Phased Manufacturing Programme (PMP), Schemes for Production Linked Incentives of various Ministries.
Further, with a view to support, facilitate and provide investor friendly ecosystem to investors investing in India, the Union Cabinet on 03rd June, 2020 has approved constitution of an Empowered Group of Secretaries (EGoS), and also Project Development Cells (PDCs) in all concerned Ministries/ Departments to fast-track investments in coordination between the Central Government and State Governments, and thereby grow the pipeline of investible projects in India to increase domestic investments and FDI inflow.
The activities under the Make in India initiative are being undertaken by several Central Government Ministries/ Departments and various State Governments. Further, Ministries formulate action plans, programmes, schemes and policies for the sectors being dealt by them. This Department does not maintain information on such formulations by the line ministries."""

In [ ]:
question_fdi = "What were the various steps taken by the government to boost domestic and foreign investment in India?"

In [ ]:
max_score = 0;
final_answer = ""
new_df = expand_split_sentences(fdi)
for new_context in new_df:
  #new_paragrapgh = new_paragrapgh + answer_question(question, answer_text)
  ans, score = answer_question(question_fdi, new_context)
  if score > max_score:
    max_score = score
    final_answer = ans
print(final_answer)
print(max_score)

Token indices sequence length is longer than the specified maximum sequence length for this model (522 > 512). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (575 > 512). Running this sequence through the model will result in indexing errors


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Token indices sequence length is longer than the specified maximum sequence length for this model (557 > 512). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (534 > 512). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (527 > 512). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (526 > 512). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (516 > 512). Running this sequence through the model will result in indexing errors


Query has 511 tokens.

Query has 502 tokens.

Query has 484 tokens.

Query has 461 tokens.

Query has 512 tokens.

Query has 512 tokens.

Query has 512 tokens.

Query has 510 tokens.

Query has 472 tokens.

Query has 445 tokens.

Query has 401 tokens.

Query has 350 tokens.

Query has 331 tokens.

Query has 284 tokens.

Query has 257 tokens.

Query has 236 tokens.

Query has 206 tokens.

Query has 174 tokens.

Query has 80 tokens.

Query has 57 tokens.

Query has 36 tokens.

national infrastructure pipeline , reduction in corporate tax , easing liquid ##ity problems of n ##bf ##cs and banks , policy measures to boost domestic manufacturing
6.569851398468018


We can see that we get a set of three activation values for each chunk.
These activation values are not our output probabilities yet. To transform these into
output probabilities, we must apply a softmax function to the output tensor.

Finally, we take the mean of the values in each class (or column) to get our final positive, negative, or neutral sentiment probability.

In [ ]:
input_ids = torch.stack(input_id_chunks)
attention_mask = torch.stack(mask_chunks)

input_dict = {
    'input_ids': input_ids.long(),
    'attention_mask': attention_mask.int()
}
input_dict

{'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
         [1, 1, 1,  ..., 1, 1, 1],
         [1, 1, 1,  ..., 0, 0, 0]], dtype=torch.int32),
 'input_ids': tensor([[  101,  2166,  5427,  ...,  1012,  2107,   102],
         [  101, 29361,  2024,  ...,  2064,  2022,   102],
         [  101,  3876,  2006,  ...,     0,     0,     0]])}

In [ ]:
outputs = model(**input_dict)
probs = torch.nn.functional.softmax(outputs[0], dim=-1)
probs = probs.mean(dim=0)
probs

**==============================================================================================================**

**Implementing Question Answering System on Multiple files**


In [ ]:
!pip install cdqa

  Using cached https://files.pythonhosted.org/packages/9f/3d/7a6b68b631d2ab54975f3a4863f3c4e9b26445353264ef01f465dc9b0208/tqdm-4.32.2-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/05/65/5248be50c55ab7429dd5c11f5e2f9f5865606b80e854ca63139ad1a584f2/torch-1.2.0-cp37-cp37m-manylinux1_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/3b/42/dc1f4820b95fbdbc9352ec9ad0f0c40db2122e1f2440ea53c7f9fbccf2b8/pandas-0.25.0-cp37-cp37m-manylinux1_x86_64.whl
ERROR: torchvision 0.9.1+cu101 has requirement torch==1.8.1, but you'll have torch 1.2.0 which is incompatible.
ERROR: torchtext 0.9.1 has requirement torch==1.8.1, but you'll have torch 1.2.0 which is incompatible.
ERROR: spacy 2.2.4 has requirement tqdm<5.0.0,>=4.38.0, but you'll have tqdm 4.32.2 which is incompatible.
ERROR: google-colab 1.0.0 has requirement pandas~=1.1.0; python_version >= "3.0", but you'll have pandas 0.25.0 which is incompatible.
ERROR: fbprophet 0.7.1 has requirement pandas>=1.0.

In [ ]:
!pip install cdqa

     |████████████████████████████████| 51kB 2.3MB/s 
     |████████████████████████████████| 102kB 4.0MB/s 
     |████████████████████████████████| 286kB 6.4MB/s 
     |████████████████████████████████| 10.4MB 5.4MB/s 
     |████████████████████████████████| 317kB 32.5MB/s 
     |████████████████████████████████| 6.7MB 26.6MB/s 
     |████████████████████████████████| 748.9MB 20kB/s 
     |████████████████████████████████| 92kB 9.2MB/s 
     |████████████████████████████████| 51kB 5.0MB/s 
     |████████████████████████████████| 1.2MB 21.5MB/s 
     |████████████████████████████████| 133kB 43.6MB/s 
     |████████████████████████████████| 901kB 39.8MB/s 
     |████████████████████████████████| 7.4MB 39.9MB/s 
     |████████████████████████████████| 81kB 9.3MB/s 
  Created wheel for cdqa: filename=cdqa-1.3.9-cp37-none-any.whl size=47640 sha256=0dd988bab228a381e20fad61721362a8db5aecf1cbdefabd844cf57a4e49b8b0
  Stored in directory: /root/.cache/pip/wheels/8b/9a/68/d3f7651ea29c30d1bebc9e9

In [ ]:
import os
import pandas as pd
from ast import literal_eval

from cdqa.utils.converters import pdf_converter
from cdqa.pipeline import QAPipeline
from cdqa.utils.download import download_model

/usr/local/lib/python3.7/dist-packages/tqdm/autonotebook/__init__.py:18: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  " (e.g. in jupyter console)", TqdmExperimentalWarning)


In [ ]:
download_model(model='bert-squad_1.1', dir='./models')

In [ ]:
!ls models

bert_qa.joblib


In [ ]:
!pip install pandas==1.1.0

     |████████████████████████████████| 10.5MB 5.4MB/s 
ERROR: fbprophet 0.7.1 has requirement tqdm>=4.36.1, but you'll have tqdm 4.32.2 which is incompatible.
ERROR: cdqa 1.3.9 has requirement pandas==0.25.0, but you'll have pandas 1.1.0 which is incompatible.
  Found existing installation: pandas 0.25.0
    Uninstalling pandas-0.25.0:
      Successfully uninstalled pandas-0.25.0


In [ ]:
df = pdf_converter(directory_path="Documents")
df.head()

title                                         paragraphs
0  Q3-2019-Amazon-Financial-Results  [Microsoft Word - AMZN-2019.9.30-EX99.1_102419...
1   Amazon-Q4-2019-Earnings-Release  [Microsoft Word - AMZN-2019.12.31-EX99.1 (10) ...
2     AMZN-Q1-2020-Earnings-Release  [Microsoft Word - Earnings Release_4.30.20_12P...
3   Q2-2020-Amazon-Earnings-Release  [AMZN-2020.06.30-EX99.1 AMAZON.COM ANNOUNCES S...
4     AMZN-Q3-2020-Earnings-Release  [Microsoft Word - AMZN-Q3-2020-Earnings-Releas...

In [ ]:
pd.set_option('display.max_colwidth', -1)
df.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  """Entry point for launching an IPython kernel.


title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

In [ ]:
cdqa_pipeline = QAPipeline(reader='./models/bert_qa.joblib', max_df=1.0)

cdqa_pipeline.fit_retriever(df=df)

100%|██████████| 231508/231508 [00:00<00:00, 314959.75B/s]


QAPipeline(reader=BertQA(adam_epsilon=1e-08, bert_model='bert-base-uncased',
                         do_lower_case=True, fp16=False,
                         gradient_accumulation_steps=1, learning_rate=5e-05,
                         local_rank=-1, loss_scale=0, max_answer_length=30,
                         n_best_size=20, no_cuda=False,
                         null_score_diff_threshold=0.0, num_train_epochs=3.0,
                         output_dir=None, predict_batch_size=8, seed=42,
                         server_ip='', server_po..._size=8,
                         verbose_logging=False, version_2_with_negative=False,
                         warmup_proportion=0.1, warmup_steps=0),
           retrieve_by_doc=False,
           retriever=BM25Retriever(b=0.75, floor=None, k1=2.0, lowercase=True,
                                   max_df=1.0, min_df=2, ngram_range=(1, 2),
                                   preprocessor=None, stop_words='english',
                                   t

In [ ]:
import joblib
joblib.dump(cdqa_pipeline, './models/bert_qa_custom.joblib')

['./models/bert_qa_custom.joblib']

In [ ]:
cdqa_pipeline=joblib.load('./models/bert_qa_custom.joblib')
cdqa_pipeline

QAPipeline(reader=BertQA(adam_epsilon=1e-08, bert_model='bert-base-uncased',
                         do_lower_case=True, fp16=False,
                         gradient_accumulation_steps=1, learning_rate=5e-05,
                         local_rank=-1, loss_scale=0, max_answer_length=30,
                         n_best_size=20, no_cuda=False,
                         null_score_diff_threshold=0.0, num_train_epochs=3.0,
                         output_dir=None, predict_batch_size=8, seed=42,
                         server_ip='', server_po..._size=8,
                         verbose_logging=False, version_2_with_negative=False,
                         warmup_proportion=0.1, warmup_steps=0),
           retrieve_by_doc=False,
           retriever=BM25Retriever(b=0.75, floor=None, k1=2.0, lowercase=True,
                                   max_df=1.0, min_df=2, ngram_range=(1, 2),
                                   preprocessor=None, stop_words='english',
                                   t

In [ ]:
query = 'How much is increase in operating cash flow?'
prediction = cdqa_pipeline.predict(query, 3)

In [ ]:
prediction

[('16 %',
  'AMZN-Q1-2020-Earnings-Release',
  'Cash Flows and Shares        Operating cash flow -- trailing twelve months (TTM) $ 30,723 $ 34,360 $ 36,029 $ 35,332 $ 38,514 $ 39,732 16 %Operating cash flow -- TTM Y/Y growth 67% 89 % 65% 33 % 25 % 16 % N/A ',
  16.822194115458565),
 ('25 %',
  'Amazon-Q4-2019-Earnings-Release',
  'Cash Flows and Shares        Operating cash flow -- trailing twelve months (TTM) $ 26,604 $ 30,723 $ 34,360 $ 36,029 $ 35,332 $ 38,514 25 %Operating cash flow -- TTM Y/Y growth 57% 67 % 89% 65% 33 % 25% N/A ',
  16.39158212549146),
 ('33 %',
  'Q3-2019-Amazon-Financial-Results',
  'Cash Flows and Shares        Operating cash flow -- trailing twelve months (TTM) $ 21,793 $ 26,604 $ 30,723 $ 34,360 $ 36,029 $ 35,332 33 %Operating cash flow -- TTM Y/Y growth 22% 57 % 67% 89% 65 % 33 % N/A ',
  16.184274739093144)]

In [ ]:
query = 'What is latest earnings per share?'
prediction = cdqa_pipeline.predict(query)

In [ ]:
prediction

('$ 7.09 $ 5.01',
 'AMZN-Q1-2020-Earnings-Release',
 'Diluted earnings per share $ 7.09  $ 5.01 ',
 13.915508470458818)

In [ ]:
query = 'How many jobs are created in 2020?'
prediction = cdqa_pipeline.predict(query)

In [ ]:
print('query: {}'.format(query))
print('answer: {}'.format(prediction[0]))
print('title: {}'.format(prediction[1]))
print('paragraph: {}'.format(prediction[2]))

query: How many jobs are created in 2020?
answer: 1.1 million
title: Q2-2020-Amazon-Earnings-Release
paragraph: Empowering Small and Medium-Sized Businesses• Amazon released its 2020 Small and Medium-Sized Business (SMB) Impact Report, highlighting how SMBs selling in its U.S. store have sold more than 3.4 billion products in the past year and created an estimated 1.1 million jobs.• In partnership with the British small business support network “Enterprise Nation,” Amazon launched the Amazon Small Business Accelerator, which aims to support more than 200,000 small businesses across the U.K. negatively impacted by the COVID-19 crisis. Amazon hosted a week-long boot camp in the U.K. to help 1,000 offline businesses get online, and offered free services, AWS credits, training, and support.• In the U.K., Amazon worked with the British Chambers of Commerce to give up to 1,000 businesses tours of Amazon fulfillment centers, helping other companies learn from the safety measures Amazon has pu

In [ ]:
query = 'General Availability of which AWS services were announced?'
prediction = cdqa_pipeline.predict(query, n_predictions=5)

In [ ]:
prediction

[('Amazon Detective',
  'AMZN-Q1-2020-Earnings-Release',
  'Amazon Web Services •  AWS announced the opening of the AWS Europe (Milan) and AWS Africa (Cape Town) Regions. AWS now spans 76 Availability Zones within 24 geographic regions, with announced plans for nine more Availability Zones and three more AWS Regions in Indonesia, Japan, and Spain.                                                        •  AWS announced the general availability of Amazon Detective, a security service that makes it easy for customers to conduct faster and more efficient investigations into security issues across their AWS workloads. Amazon Detective automatically collects log data from a customer’s resources and uses machine learning, statistical analysis, and graph theory to build interactive visualizations that help customers analyze, investigate, and quickly identify the root cause of potential security issues or suspicious activities.  •  AWS announced the general availability of Amazon Keyspaces (for

In [ ]:
query = 'What is the impact of COVID on business?'
prediction = cdqa_pipeline.predict(query, n_predictions=5)

In [ ]:
prediction

[('negatively impacted by the COVID-19 crisis',
  'Q2-2020-Amazon-Earnings-Release',
  'Empowering Small and Medium-Sized Businesses• Amazon released its 2020 Small and Medium-Sized Business (SMB) Impact Report, highlighting how SMBs selling in its U.S. store have sold more than 3.4 billion products in the past year and created an estimated 1.1 million jobs.• In partnership with the British small business support network “Enterprise Nation,” Amazon launched the Amazon Small Business Accelerator, which aims to support more than 200,000 small businesses across the U.K. negatively impacted by the COVID-19 crisis. Amazon hosted a week-long boot camp in the U.K. to help 1,000 offline businesses get online, and offered free services, AWS credits, training, and support.• In the U.K., Amazon worked with the British Chambers of Commerce to give up to 1,000 businesses tours of Amazon fulfillment centers, helping other companies learn from the safety measures Amazon has put in place within its ow

**==============================================================================================================**